/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {


    public static void main(String[] args) {

        Bitmap test = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "mirror-natural1.bmp");
        test.bluifyRed();
    }
}
